### ISSUE TITLE
Raspberry Pi 3 - Bluetooth

### ISSUE THREAD

**Issue by JaiSpicer** [long-exposure/potsbliz-src#2]
When searching for a device get an error from the GUI 
![errir name](https://cloud.githubusercontent.com/assets/5627328/15306961/36a57a20-1c12-11e6-8a86-a3568358abf0.PNG)

a fix for this would be awesome as i want to use the Bluetooth functionality in a project

**Comment by JaiSpicer** [comment]
Stopped the error it was because of the default SIP account

**Comment by davidferguson** [comment]
Did you ever get this working with the Pi 3? I'm asking because I'm having issues with the audio not connecting over bluetooth (https://github.com/long-exposure/potsbliz-src/issues/3) and I'm also using a Pi 3.
